# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy_to_preview:
    runs-on: ubuntu-18.04
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2

      # ( Build to ./dist or other directory... )
      - name: Install Client
        run: npm ci
      
      - name: Build Client
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-branch: dummy
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          overwrites-pull-request-comment: false
          enable-commit-comment: false
          production-deploy: false
          enable-commit-status: true
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  deploy_to_dev:
    name: Deploy to Dev 
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # environment: 
      # name: dev
      # url: 'https://dev.margin-free.netlify.app'
    steps:
      - uses: actions/checkout@v2

      - name: Install Client
        run: npm ci
      
      - name: Build Client
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-branch: dummy
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions to dev"
          enable-pull-request-comment: false
          overwrites-pull-request-comment: false
          enable-commit-comment: false
          production-deploy: false
          enable-commit-status: true
          github-deployment-environment: dev
          alias: dev
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
